spring:
  application:
    name: zipkin-server
server:
  port: 9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka    #注册到指定的eureka
  instance:
    instance-id: zipkin-server              #定义微服务的名称
    prefer-ip-address: true                        #是否显示IP和端口
management:
  metrics:
    web:
      server:
        auto-time-requests: false