server:
  port: 9080
  servlet:
    context-path: /

spring:
  application:
    name: config-service   #定义服务名称
  config:
    name: config-service   #定义配置文件名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gongxufan/springcloud-config #连接远程git账户
          search-paths: /** #查找git仓库的路径
          label: master #查找的git分支
#          username: #私有仓库需要配置用户名和密码
#          password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: config-service-9080   #定义微服务的名称
    prefer-ip-address: true            #是否显示IP和端口
